### ISSUE TITLE
Typo in CompoundTag#L218

### ISSUE THREAD

**Issue by Louis9902** [InventivetalentDev/NBTLibrary#4]
While testing something I found a little typo in [CompoundTag#L218](https://github.com/InventivetalentDev/NBTLibrary/blob/master/src/main/java/org/inventivetalent/nbt/CompoundTag.java#L218), or is it intended to write `"TAG_Compund"` instead of `"TAG_Compound"`

**Comment by InventivetalentDev** [comment]
Thanks :)
